server:
  port: 3000
  servlet:
    context-path: /api


spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      url: jdbc:mysql:///senbao
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver
#  graphql:
#    cors:
#      allowed-origins: "*"
#      allowed-methods: "*"
#      allowed-headers: "*"
#      allow-credentials: true


# mybatis-plus的配置
mybatis-plus:
  type-aliases-package: com.senbao.pojo
  global-config:
    db-config:
      logic-delete-field: isDeleted  #全局逻辑删除
      id-type: auto #主键策略自增长

jwt:
  token:
    tokenExpiration: 120
    tokenSignKey: senbao123

